#+TITLE: 纯粹理性批判

* 纯粹理性批判

** 导论

*** 论纯粹知识与经验性知识的区别

1. 我们的一切 *知识* 都从 *经验* 开始。

*经验* 的构成。 *对象* 激动感官引起表象，并由 *知性活动* 将表象加以比较，进而联结或分离，将感性印象加工成经验。

*按照时间* ，没有任何只是是 *先行于* 经验的。

2. 尽管一切只是都是 *以* 经验开始的，但并不因此都是 *从经验中* 发源的。

可能我们的知识是由印象激发并从我们本身的认识能力中拿出的一个复合物。

3. *先天的（a priori）* 与 *经验性的 (empirische)*

4. *先天的知识* ：完全不依赖于任何经验所发生的知识。

5. 先天知识中那些完全没有掺杂任何经验的东西的知识则成为 *纯粹的* 。

   先天的知识可能从某些普遍规则中引出来，而这些普遍规则又与规则相关。

*** 我们拥有某些先天知识，甚至普遍的知性也从不缺少他们

*首先* ，如果有一个命题与它的 *必然性* 一起被同时想到，那么它就是一个 *先天判断* 。

如果它不再由别的命题引出，除非它本身是一个有效的必然命题，它就是一个 *完全先天的命题* 。

*其次* ，经验永远也不给自己的判断以真正的或严格的 *普遍性* ，而只是（通过归纳）给它们以假定的、相比较的普遍性。而经验的普遍性指示把对大多数场合下使用的 *有效性* 提升到对一切场合都使用的有效性。（经验的 *普遍性* 是一切场合下的 *有效性* 。）

但严格的普遍性在本质上属于一个判断，这种普遍性表示该判断是一个特别的知识来源，也就是一种 *先天的认识能力* 。

于是， *必然性* 和 *严格普遍性* 就是一种 *先天的认识的可靠标志* ，而两者 *不可互相分割的从属* 。

不难之处，在人类知识中会有这样一些必然和严格意义上普遍的纯粹先天判断。（这样一种判断很明显是来源于主体的，就是主体内部存在的一种认识结构。）经验原理的不可永久回退性，暗示了先天性判断的存在。（这里，第二版的叙述比第一版更 pure 。）

*** 哲学需要一门科学来规定一切先天知识的可能性、原则和范围

有某些知识甚至离开了一切可能经验的领域，并通过任何地方都不能提供经验中相应对象的那些概念而装作要使我们的判断范围扩大到超出一切经验界限之外。

正是出于这样一种位置，于是经验就不能提供任何线索、更不能给与校正。

纯粹理性本身的这些不可回避的课题就是 *上帝* 、 *自由* 和 *不朽* 。（为什么？）而对应的那门科学就是形而上学，它的方法在开始是独断的，也就是不预先检验理性是否有能力完成这项工作。

知性一开始感受到了了感官世界的限制，进入了纯粹知性的真空。

*** 分析判断与综合判断的区别

分析判断：谓词 B 属于主词 A ，是（隐蔽地）包含在 A 这个概念中的东西。

综合判断：谓词 B 完全外在于概念 A 。

前者可以被称为说明性的判断，后者可以称为扩展性的判断。

经验判断就其本身而言 *全都是综合的* 。

*** 在理性的一切理论科学中都包含有先天综合判断作为原则

1. 数学的判断诠释综合的。

真正的数学命题总是先天判断。

纯粹数学命题不包含经验性的知识。

数学的命题包含了人的直观。

2. 自然科学（物理学）包含先天综合判断作为自身中的原则。

3. 形而上学，即使我们把它仅仅看作一门至今还只是在尝试、但却由于人类理性的本性而不可缺少的科学，也应该包含先天综合的只是。

*** 纯粹理性的总课题

先天综合判断是如何可能的？

*** 在纯粹理性批判名下的一门特殊科学的理念和划分

因为理性是提供出先天只是的诸原则的能力。所以纯粹理性就是包含有完全先天地认识某物的诸原则的理性。

我把一切与其说是关注于对象，不如说是一般地关注于我们有关对象的、就其应当为先天可能的而言的认识方式的知识，称之为 *先验的* 。

先验批判。

人类知识有两大主干，感性和知性，通过前者，对象被给予我们，而通过后者，对象则被我们思维。

** 一、先验要素论

*** 1

知识与对象直接关联所依赖的东西，以及作为关联对象的手段的东西，就是 *直观* 。

- 直观只是对象被给予我们时才发生，至少只是通过对象以某种法师刺激信仰才是可能的。

我们通过被对象刺激的方式获得表象的能力称做 *感性* 。借助于感性，对象被给予我们，且 *只有感性才给我们提供直观* 。
直观通过知性而被思维，而从知性产生出 *概念* 。

一切思维，都必须借助于某些标志最终与直观、与感性发生关系，因为以别的方式不可能有任何对象给予我们。

当我们被一个对象所刺激时，它表象能力上所产生的结果就是 *感觉* 。通过感觉与对象发生关系的直观就叫做 *经验性的直观* 。一个经验性直观未被规定的 *现象（显象 appearance）* 。

在显象中，我把与感觉相应的东西称为显象的 *质料* 。
