#+TITLE: 纯粹理性批判

* 纯粹理性批判

** 导论

*** 一、论纯粹知识与经验性知识的区别

1. 我们的一切 *知识* 都从 *经验* 开始。

*经验* 的构成。 *对象* 激动感官引起表象，并由 *知性活动* 将表象加以比较，进而联结或分离，将感性印象加工成经验。

*按照时间* ，没有任何只是是 *先行于* 经验的。

2. 尽管一切只是都是 *以* 经验开始的，但并不因此都是 *从经验中* 发源的。

可能我们的知识是由印象激发并从我们本身的认识能力中拿出的一个复合物。

3. *先天的（a priori）* 与 *经验性的 (empirische)*

4. *先天的知识* ：完全不依赖于任何经验所发生的知识。

5. 先天知识中那些完全没有掺杂任何经验的东西的知识则成为 *纯粹的* 。

   先天的知识可能从某些普遍规则中引出来，而这些普遍规则又与规则相关。

*** 二、我们拥有某些先天知识，甚至普遍的知性也从不缺少他们

*首先* ，如果有一个命题与它的 *必然性* 一起被同时想到，那么它就是一个 *先天判断* 。

如果它不再由别的命题引出，除非它本身是一个有效的必然命题，它就是一个 *完全先天的命题* 。

*其次* ，经验永远也不给自己的判断以真正的或严格的 *普遍性* ，而只是（通过归纳）给它们以假定的、相比较的普遍性。而经验的普遍性指示把对大多数场合下使用的 *有效性* 提升到对一切场合都使用的有效性。（经验的 *普遍性* 是一切场合下的 *有效性* 。）

但严格的普遍性在本质上属于一个判断，这种普遍性表示该判断是一个特别的知识来源，也就是一种 *先天的认识能力* 。

于是， *必然性* 和 *严格普遍性* 就是一种 *先天的认识的可靠标志* ，而两者 *不可互相分割的从属* 。

不难之处，在人类知识中会有这样一些必然和严格意义上普遍的纯粹先天判断。（这样一种判断很明显是来源于主体的，就是主体内部存在的一种认识结构。）经验原理的不可永久回退性，暗示了先天性判断的存在。（这里，第二版的叙述比第一版更 pure 。）

*** 哲学需要一门科学来规定一切先天知识的可能性、原则和范围

有某些知识甚至离开了一切可能经验的领域，并通过任何地方都不能提供经验中相应对象的那些概念而装作要使我们的判断范围扩大到超出一切经验界限之外。

正是出于这样一种位置，于是经验就不能提供任何线索、更不能给与校正。

纯粹理性本身的这些不可回避的课题就是 *上帝* 、 *自由* 和 *不朽* 。（为什么？）而对应的那门科学就是形而上学，它的方法在开始是独断的，也就是不预先剪影姐理性是否有能力完成这项工作。
